feat: Docker image override with env, update tests, constraint v1.24.3

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -1,26 +1,25 @@
-#ddev-generated
-
 name: phpmyadmin
 
 project_files:
-- docker-compose.phpmyadmin.yaml
-- docker-compose.phpmyadmin_norouter.yaml
-- commands/host/phpmyadmin
+  - docker-compose.phpmyadmin.yaml
+  - docker-compose.phpmyadmin_norouter.yaml
+  - commands/host/phpmyadmin
 
 pre_install_actions:
-  # Ensure we're on DDEV 1.23+. It's need for the `phpmyadmin` command (launch by port).
   - |
-    #ddev-nodisplay
-    #ddev-description:Checking DDEV version
-    (ddev debug capabilities | grep corepack >/dev/null) || (echo "Please upgrade DDEV to v1.23+ to use this add-on." && false)
+    #ddev-description:Check for db service
+    if ddev debug configyaml 2>/dev/null | grep omit_containers | grep -q db; then
+      echo "Unable to install the add-on because no db service was found"
+      exit 1
+    fi
+
+ddev_version_constraint: '>= v1.24.3'
 
 post_install_actions:
   - |
     #ddev-description:If router disabled, directly expose port
-    #
     if ( {{ contains "ddev-router" (list .DdevGlobalConfig.omit_containers | toString) }} ); then
       printf "#ddev-generated\nservices:\n  phpmyadmin:\n    ports:\n      - 8036:80\n" > docker-compose.phpmyadmin_norouter.yaml
     fi
   - |
     echo "You can now use 'ddev phpmyadmin' to launch PhpMyAdmin"
-
